// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2mQ8uPLd_jQvHOVtW20iFh78UawUmXd8',
    appId: '1:851589588269:web:f203ab93bfaeac5392dfa4',
    messagingSenderId: '851589588269',
    projectId: 'notifeye-f509f',
    authDomain: 'notifeye-f509f.firebaseapp.com',
    databaseURL: 'https://notifeye-f509f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notifeye-f509f.appspot.com',
    measurementId: 'G-69DJ737YMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyAx-UfW2r0Vp2VUyMozC_grVGuIeTNks',
    appId: '1:851589588269:android:24150ea125119d6a92dfa4',
    messagingSenderId: '851589588269',
    projectId: 'notifeye-f509f',
    databaseURL: 'https://notifeye-f509f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notifeye-f509f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Gg6g_kiT-D96g-K2-WVZzT5xIPO7NxA',
    appId: '1:851589588269:ios:62cf9cba65261f5492dfa4',
    messagingSenderId: '851589588269',
    projectId: 'notifeye-f509f',
    databaseURL: 'https://notifeye-f509f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notifeye-f509f.appspot.com',
    iosBundleId: 'com.example.crime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Gg6g_kiT-D96g-K2-WVZzT5xIPO7NxA',
    appId: '1:851589588269:ios:4da077463c6b449692dfa4',
    messagingSenderId: '851589588269',
    projectId: 'notifeye-f509f',
    databaseURL: 'https://notifeye-f509f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notifeye-f509f.appspot.com',
    iosBundleId: 'com.example.crime.RunnerTests',
  );
}
